---
name: ((deployment_name))

instance_groups:
- name: redis
  azs: [((default_az))]
  instances: ((node_count))
  vm_type: ((default_vm_type))
  stemcell: default
  persistent_disk_type: ((default_persistent_disk_type))
  networks:
  - name: ((default_network))
  jobs:
  - name: redis
    release: ((release_name))
    properties:
      bind: ((redis_bind))
      password: ((redis_password))
      admin_password: ((redis_admin_password))
      exporter_password: ((redis_exporter_password))
      maxmemory: ((redis_maxmemory))
      maxmemory_policy: ((redis_maxmemory_policy))
  - name: redis_check
    release: ((release_name))
  - name: redis_broker
    release: ((release_name))
    properties:
      bind: ((redis_bind))
      password: ((redis_broker_password))
  - name: redis_broker_check
    release: ((release_name))
  - name: redis_exporter
    release: ((release_name))

variables:
- name: redis_password
  type: password
  parameters:
    length: ((password_length))
- name: redis_admin_password
  type: password
  parameters:
    length: ((password_length))
- name: redis_exporter_password
  type: password
  parameters:
    length: ((password_length))
- name: redis_broker_password
  type: password
  parameters:
    length: ((password_length))

stemcells:
- alias: default
  os: ((stemcell_os))
  version: "((stemcell_version))"

releases:
- name: ((release_name))
  version: latest

update:
  canaries: 2
  canary_watch_time: 30000-60000
  max_in_flight: 2
  update_watch_time: 30000-60000
  serial: false
