---
name: ((deployment_name))

instance_groups:
- name: redis-master
  azs: [((default_az))]
  instances: ((master_node_count))
  vm_type: ((default_vm_type))
  stemcell: default
  persistent_disk: ((persistent_disk_size))
  networks:
  - name: ((default_network))
  jobs:
  - name: haveged
    release: ((release_name))
  - name: redis
    release: ((release_name))
    consumes:
      slave_conn: nil
      redis_sentinel_conn: {from: sentinel_master}
      sentinel_slave_conn: {from: sentinel_slave}
    properties:
      bind: ((redis_bind))
      port: ((redis_port))
      password: ((redis_password))
      admin_password: ((redis_admin_password))
      exporter_password: ((redis_exporter_password))
      replica_password: ((redis_replica_password))
      sentinel_password: ((redis_sentinel_user_password))
      maxmemory: ((redis_maxmemory))
      maxmemory_policy: ((redis_maxmemory_policy))
      replication: ((redis_replication))
      tls: ((redis_tls))
      tls_dh_length: ((redis_dh_length))
      tls_replication: ((redis_tls_replication))
  - name: redis_check
    release: ((release_name))
    consumes:
      slave_conn: nil
      redis_sentinel_conn: {from: sentinel_master}
      sentinel_slave_conn: {from: sentinel_slave}
  - name: redis_exporter
    release: ((release_name))
    consumes:
      redis_sentinel_conn: {from: sentinel_master}
    properties:
      skip_tls_verification: ((redis_exporter_skip_tls_verification))
  - name: redis_sentinel
    release: ((release_name))
    provides:
      redis_sentinel_conn: {as: sentinel_master}
    consumes:
      redis_sentinel_conn: {from: sentinel_master}
    properties:
      bind: ((redis_bind))
      port: ((redis_sentinel_port))
      password: ((redis_sentinel_password))
      tls: ((redis_sentinel_tls))
      tls_ca_certificate: ((sentinel_ca_certificate))
      tls_ca_private_key: ((sentinel_ca_private_key))
      tls_dh_length: ((redis_dh_length))
      tls_replication: ((redis_tls_replication))
- name: sentinel-slave
  azs: [((default_az))]
  instances: ((slave_node_count))
  vm_type: ((default_vm_type))
  stemcell: default
  persistent_disk: ((persistent_disk_size))
  networks:
  - name: ((default_network))
  jobs:
  - name: haveged
    release: ((release_name))
  - name: redis_sentinel
    release: ((release_name))
    provides:
      redis_sentinel_conn: {as: sentinel_slave}
    consumes:
      redis_sentinel_conn: {from: sentinel_master}
    properties:
      tls_dh_length: ((redis_dh_length))
- name: broker
  azs: [((default_az))]
  instances: 1
  vm_type: ((default_vm_type))
  stemcell: default
  networks:
  - name: ((default_network))
  jobs:
  - name: haveged
    release: ((release_name))
  - name: redis_broker
    release: ((release_name))
    consumes:
      slave_conn: nil
      redis_sentinel_conn: {from: sentinel_master}
      sentinel_slave_conn: {from: sentinel_slave}
    properties:
      bind: ((redis_bind))
      password: ((redis_broker_password))
      tls: ((redis_broker_tls))
  - name: redis_broker_check
    release: ((release_name))

variables:
- name: redis_password
  type: password
  parameters:
    length: ((password_length))
- name: redis_admin_password
  type: password
  parameters:
    length: ((password_length))
- name: redis_exporter_password
  type: password
  parameters:
    length: ((password_length))
- name: redis_replica_password
  type: password
  parameters:
    length: ((password_length))
- name: redis_sentinel_user_password
  type: password
  parameters:
    length: ((password_length))
- name: redis_sentinel_password
  type: password
  parameters:
    length: ((password_length))
- name: redis_broker_password
  type: password
  parameters:
    length: ((password_length))

stemcells:
- alias: default
  os: ((stemcell_os))
  version: "((stemcell_version))"

releases:
- name: ((release_name))
  version: latest

update:
  canaries: 2
  canary_watch_time: 60000-120000
  max_in_flight: 2
  update_watch_time: 60000-120000
  serial: false
