---
name: ((deployment_name))

instance_groups:
- name: redis
  azs: [((default_az))]
  instances: ((node_count))
  vm_type: ((default_vm_type))
  stemcell: default
  networks:
  - name: ((default_network))
  jobs:
  - name: redis
    release: ((release_name))
    consumes:
      slave_conn: nil
      redis_sentinel_conn: nil
      sentinel_slave_conn: nil
    properties:
      bind: ((redis_bind))
      password: ((redis_password))
      maxmemory: ((redis_maxmemory))
      maxmemory_policy: ((redis_maxmemory_policy))
      cluster_enabled: ((redis_cluster_enabled))
      cluster_replicas_per_node: ((replicas_per_node_count))
      rename_config_command: ((redis_rename_config_command))
      rename_save_command: ((redis_rename_save_command))
      rename_bgsave_command: ((redis_rename_bgsave_command))
      rename_bgrewriteaof_command: ((redis_rename_bgrewriteaof_command))
      rename_monitor_command: ((redis_rename_monitor_command))
      rename_debug_command: ((redis_rename_debug_command))
      rename_shutdown_command: ((redis_rename_shutdown_command))
      rename_slaveof_command: ((redis_rename_slaveof_command))
      rename_replicaof_command: ((redis_rename_replicaof_command))
      rename_sync_command: ((redis_rename_sync_command))
  - name: redis_check
    release: ((release_name))
    consumes:
      slave_conn: nil
      redis_sentinel_conn: nil
      sentinel_slave_conn: nil
  - name: redis_exporter
    release: ((release_name))
- name: broker
  azs: [((default_az))]
  instances: 1
  vm_type: ((default_vm_type))
  stemcell: default
  networks:
  - name: ((default_network))
  jobs:
  - name: redis_broker
    release: ((release_name))
    properties:
      bind: ((redis_bind))
      password: ((broker_password))
    consumes:
      slave_conn: nil
      redis_sentinel_conn: nil
      sentinel_slave_conn: nil
  - name: redis_broker_check
    release: ((release_name))

variables:
- name: redis_password
  type: password
- name: redis_rename_config_command
  type: password
- name: redis_rename_save_command
  type: password
- name: redis_rename_bgsave_command
  type: password
- name: redis_rename_bgrewriteaof_command
  type: password
- name: redis_rename_monitor_command
  type: password
- name: redis_rename_debug_command
  type: password
- name: redis_rename_shutdown_command
  type: password
- name: redis_rename_slaveof_command
  type: password
- name: redis_rename_replicaof_command
  type: password
- name: redis_rename_sync_command
  type: password
- name: broker_password
  type: password

stemcells:
- alias: default
  os: ((stemcell_os))
  version: "((stemcell_version))"

releases:
- name: ((release_name))
  version: latest

update:
  canaries: 2
  canary_watch_time: 60000-120000
  max_in_flight: 2
  update_watch_time: 60000-120000
  serial: false
