---
name: ((deployment_name))

instance_groups:
- name: redis-master
  azs: [((default_az))]
  instances: ((master_node_count))
  vm_type: ((default_vm_type))
  stemcell: default
  persistent_disk: ((persistent_disk_size))
  networks:
  - name: ((default_network))
  jobs:
  - name: redis
    release: ((release_name))
    provides:
      redis_conn: {as: master}
    consumes:
      redis_conn: {from: master}
      slave_conn: nil
      redis_sentinel_conn: {from: sentinel_master}
      sentinel_slave_conn: {from: sentinel_slave}
    properties:
      bind: ((redis_bind))
      maxmemory: ((redis_maxmemory))
      maxmemory_policy: ((redis_maxmemory_policy))
      replication: ((redis_replication))
      password: ((redis_password))
      rename_config_command: ((redis_rename_config_command))
      rename_save_command: ((redis_rename_save_command))
      rename_bgsave_command: ((redis_rename_bgsave_command))
      rename_bgrewriteaof_command: ((redis_rename_bgrewriteaof_command))
      rename_monitor_command: ((redis_rename_monitor_command))
      rename_debug_command: ((redis_rename_debug_command))
      rename_shutdown_command: ((redis_rename_shutdown_command))
      rename_slaveof_command: ((redis_rename_slaveof_command))
      rename_replicaof_command: ((redis_rename_replicaof_command))
      rename_sync_command: ((redis_rename_sync_command))
  - name: redis_check
    release: ((release_name))
    consumes:
      redis_conn: {from: master}
      slave_conn: nil
      redis_sentinel_conn: {from: sentinel_master}
      sentinel_slave_conn: {from: sentinel_slave}
  - name: redis_exporter
    release: ((release_name))
    consumes:
      redis_conn: {from: master}
  - name: redis_sentinel
    release: ((release_name))
    provides:
      redis_sentinel_conn: {as: sentinel_master}
    consumes:
      redis_conn: {from: master}
      redis_sentinel_conn: {from: sentinel_master}
    properties:
      bind: ((redis_bind))
      password: ((sentinel_password))
  - name: redis_sentinel_exporter
    release: ((release_name))
    consumes:
      redis_sentinel_conn: {from: sentinel_master}
- name: sentinel-slave
  azs: [((default_az))]
  instances: ((slave_node_count))
  vm_type: ((default_vm_type))
  stemcell: default
  persistent_disk: ((persistent_disk_size))
  networks:
  - name: ((default_network))
  jobs:
  - name: redis_sentinel
    release: ((release_name))
    provides:
      redis_sentinel_conn: {as: sentinel_slave}
    consumes:
      redis_conn: {from: master}
      redis_sentinel_conn: {from: sentinel_master}
  - name: redis_sentinel_exporter
    release: ((release_name))
    consumes:
      redis_sentinel_conn: {from: sentinel_master}
- name: broker
  azs: [((default_az))]
  instances: 1
  vm_type: ((default_vm_type))
  stemcell: default
  networks:
  - name: ((default_network))
  jobs:
  - name: redis_broker
    release: ((release_name))
    consumes:
      redis_conn: {from: master}
      slave_conn: nil
      redis_sentinel_conn: {from: sentinel_master}
      sentinel_slave_conn: {from: sentinel_slave}
    properties:
      bind: ((redis_bind))
      password: ((broker_password))
  - name: redis_broker_check
    release: ((release_name))

variables:
- name: redis_password
  type: password
- name: sentinel_password
  type: password
- name: redis_rename_config_command
  type: password
- name: redis_rename_save_command
  type: password
- name: redis_rename_bgsave_command
  type: password
- name: redis_rename_bgrewriteaof_command
  type: password
- name: redis_rename_monitor_command
  type: password
- name: redis_rename_debug_command
  type: password
- name: redis_rename_shutdown_command
  type: password
- name: redis_rename_slaveof_command
  type: password
- name: redis_rename_replicaof_command
  type: password
- name: redis_rename_sync_command
  type: password
- name: broker_password
  type: password

stemcells:
- alias: default
  os: ((stemcell_os))
  version: "((stemcell_version))"

releases:
- name: ((release_name))
  version: latest

update:
  canaries: 2
  canary_watch_time: 60000-120000
  max_in_flight: 4
  update_watch_time: 60000-120000
  serial: true
